import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProviders } from "@/providers/QueryProvider";
import SheetProvider from "@/providers/SheetProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OUTBREAK",
  description: "Generated by Nikhil Mishra",
  icons: {
    icon: '/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <QueryProviders>
          <SheetProvider />
          <Toaster />
          {children}
          </QueryProviders>

        </body>
      </html>
    </ClerkProvider>
  );
}
